version: 2
storybook-rn:
  appium:
    server: http://localhost:4723
    capabilities:
      platformName: iOS
      "appium:platformVersion": "18.4"
      "appium:deviceName": "iPhone 16"
      "appium:bundleId": "com.anonymous.RNStorybookFixture"
      "appium:automationName": XCUITest
      "appium:newCommandTimeout": 30
  storybook:
    websocketHost: 127.0.0.1
    websocketPort: 7007
    waitForReadyMs: 4000
  include:
    - "**/*"
  skip: []
