import command from '@percy/cli-command';
import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * `npx @percy/cli storybook-rn:init`
 *
 * Scaffolds a working configuration so a customer can go from zero to first
 * Percy build in minutes. Specifically:
 *
 *   1. .percy.yml — with iOS Simulator capabilities + 127.0.0.1 host pinning
 *      (avoids IPv4/IPv6 localhost mismatch on macOS).
 *
 *   2. metro.config.js — wraps the customer's Metro config with
 *      withStorybook({ websockets: { host: '127.0.0.1', port: 7007 } })
 *      so the channel server binds the same address family the SDK dials.
 *      Skips overwrite if metro.config.js already exists; prints a copy-paste
 *      patch instead.
 *
 *   3. Prints the one-line patch the customer must apply to their
 *      .rnstorybook/index.{ts,js} — `enableWebsockets: true` in the
 *      getStorybookUI() options. (Defaults to false in @storybook/react-native;
 *      without it, STORYBOOK_WEBSOCKET is set but never connected.)
 *
 *   4. Prints next-step commands.
 *
 * No AST editing — only file creation and copy-paste output. Idempotent.
 */
export default command('init', {
  description: 'Scaffold .percy.yml + metro.config.js + print next steps for Storybook RN integration.',
}, async ({ log }) => {
  const cwd = process.cwd();

  // 1. .percy.yml
  const percyYmlPath = path.join(cwd, '.percy.yml');
  if (await pathExists(percyYmlPath)) {
    log.warn(`.percy.yml already exists at ${percyYmlPath} — skipping.`);
  } else {
    await fs.writeFile(percyYmlPath, PERCY_YML_TEMPLATE, 'utf8');
    log.info(`✓ Wrote ${percyYmlPath}`);
  }

  // 2. metro.config.js
  const metroPath = path.join(cwd, 'metro.config.js');
  if (await pathExists(metroPath)) {
    log.warn(`metro.config.js already exists at ${metroPath} — skipping.`);
    log.info('  Apply this patch manually so the Storybook channel server uses the host the SDK expects:');
    log.info(METRO_PATCH_SNIPPET);
  } else {
    await fs.writeFile(metroPath, METRO_CONFIG_TEMPLATE, 'utf8');
    log.info(`✓ Wrote ${metroPath}`);
  }

  // 3. Addon snippet for .rnstorybook/index
  log.info('');
  log.info('Almost done — one manual edit required (Storybook RN does not enable the channel by default):');
  log.info(STORYBOOK_INDEX_SNIPPET);

  // 4. Next steps
  log.info('');
  log.info('Next steps:');
  log.info('  1. Edit .percy.yml — set bundleId/platform to match your app.');
  log.info('  2. Add `enableWebsockets: true` to your getStorybookUI() options (snippet above).');
  log.info('  3. Boot your simulator + Appium server, install your dev build, then:');
  log.info('       export PERCY_TOKEN=...');
  log.info('       npx percy storybook-rn:doctor          # verify the stack is wired');
  log.info('       npx percy exec -- npx percy storybook-rn   # take snapshots');
  log.info('');
  log.info('Full setup walkthrough: see the SETUP.md doc in @percy/storybook-react-native.');
});

const PERCY_YML_TEMPLATE = `version: 2
storybook-rn:
  appium:
    server: http://localhost:4723
    capabilities:
      platformName: iOS
      "appium:platformVersion": "18.4"
      "appium:deviceName": "iPhone 16"
      # Replace with your app's bundle identifier (Info.plist > CFBundleIdentifier).
      "appium:bundleId": "com.yourcompany.yourapp"
      "appium:automationName": XCUITest
      "appium:newCommandTimeout": 30
  storybook:
    # 127.0.0.1 (NOT 'localhost') — avoids IPv4/IPv6 localhost mismatch on macOS.
    websocketHost: 127.0.0.1
    websocketPort: 7007
    # Backstop wait for stories that lack a deterministic ready signal. The
    # /select-story-sync endpoint usually acks faster than this.
    waitForReadyMs: 4000
  include:
    - "**/*"
  skip: []
`;

const METRO_CONFIG_TEMPLATE = `// Generated by \`@percy/cli storybook-rn:init\`.
// Wraps Metro with Storybook RN's channel server on port 7007. The Percy SDK
// connects to this server via HTTP /select-story-sync to drive story selection.

const { getDefaultConfig } = require('expo/metro-config'); // for Expo projects
// For bare RN: const { getDefaultConfig } = require('@react-native/metro-config');
const { withStorybook } = require('@storybook/react-native/metro/withStorybook');

const config = getDefaultConfig(__dirname);

module.exports = withStorybook(config, {
  configPath: './.rnstorybook',
  // Pin to 127.0.0.1 (NOT 'auto' or 'localhost') — keeps server bind, device
  // connection, and SDK probe on the same address family. Without this, on
  // macOS the WS server binds ::1 (IPv6) while undici fetch dials 127.0.0.1
  // (IPv4) and the connection silently never establishes.
  websockets: { host: '127.0.0.1', port: 7007 },
});
`;

const METRO_PATCH_SNIPPET = `
    const { withStorybook } = require('@storybook/react-native/metro/withStorybook');

    module.exports = withStorybook(config, {
      configPath: './.rnstorybook',
      websockets: { host: '127.0.0.1', port: 7007 },  // pin IPv4 — see SETUP.md
    });
`;

const STORYBOOK_INDEX_SNIPPET = `
    // .rnstorybook/index.{ts,js}
    const StorybookUIRoot = view.getStorybookUI({
      storage: { /* your existing storage */ },
      enableWebsockets: true,    // ← add this line; defaults to false in @storybook/react-native
    });
`;

/** @param {string} p */
async function pathExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
